using System.Text;
using RagOpenSearch.Domain.Entities;
using RagOpenSearch.Domain.Services;

namespace RagOpenSearch.Infrastructure.Llm;

public sealed class MockLlmService : ILlmService
{
    public Task<string> GenerateAnswerAsync(
        string question,
        IReadOnlyList<SearchHit> evidence,
        CancellationToken cancellationToken = default)
    {
        if (evidence.Count == 0)
        {
            return Task.FromResult(
                "I could not find relevant content in the indexed documents. Upload documents and try again.");
        }

        var sb = new StringBuilder();
        sb.AppendLine($"Based on the retrieved sources for: \"{question.Trim()}\"");
        sb.AppendLine();
        sb.AppendLine(evidence[0].Content.Trim());
        if (evidence.Count > 1)
        {
            sb.AppendLine();
            sb.AppendLine($"Additional support came from {evidence.Count - 1} more chunk(s): "
                          + string.Join(", ", evidence.Skip(1).Select(e => $"{e.FileName}#{e.ChunkIndex}")));
        }

        sb.AppendLine();
        sb.Append("(Generated by Mock LLM — set Llm:Provider=OpenAI and provide an API key for GPT answers.)");
        return Task.FromResult(sb.ToString());
    }
}
